/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    column: Column;
    members: Member;
    sponsors: Sponsor;
    events: Event;
    gallery: Gallery;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    column: ColumnSelect<false> | ColumnSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
    freeschool: Freeschool;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    freeschool: FreeschoolSelect<false> | FreeschoolSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "column".
 */
export interface Column {
  id: number;
  title: string;
  slug: string;
  publishedDate: string;
  category: 'free_school' | 'event' | 'other';
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  type: 'staff' | 'collaborator';
  collaborationType?: string | null;
  isRepresentative?: boolean | null;
  name: string;
  role?: string | null;
  description?: string | null;
  fullDescription?: string | null;
  favoriteWords?: string | null;
  hobbies?: string | null;
  qualifications?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  pastQualifications?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  color?: ('bg-pink' | 'bg-blue' | 'bg-yellow' | 'bg-lime' | 'bg-green') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  type: 'event' | 'free_school' | 'other';
  date?: string | null;
  endDate?: string | null;
  isAllDay?: boolean | null;
  recurringDays?: ('sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat')[] | null;
  link?: string | null;
  isHighlight?: boolean | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  image: number | Media;
  shotDate?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * サイト管理用ユーザーアカウント
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 管理者以外変更できません
   */
  role: 'admin' | 'editor';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'column';
        value: number | Column;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "column_select".
 */
export interface ColumnSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedDate?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  image?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  type?: T;
  collaborationType?: T;
  isRepresentative?: T;
  name?: T;
  role?: T;
  description?: T;
  fullDescription?: T;
  favoriteWords?: T;
  hobbies?: T;
  qualifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  pastQualifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  image?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  endDate?: T;
  isAllDay?: T;
  recurringDays?: T;
  link?: T;
  isHighlight?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  shotDate?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  intro_message?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mission?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  history_years?: number | null;
  concept?: {
    title?: string | null;
    subtitle?: string | null;
    main_image?: (number | null) | Media;
    description_1?: string | null;
    description_2?: string | null;
    activities?:
      | {
          text?: string | null;
          color?: ('bg-lime' | 'bg-yellow' | 'bg-blue' | 'bg-pink' | 'bg-purple') | null;
          id?: string | null;
        }[]
      | null;
    features?:
      | {
          image?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  overview?: {
    org_name?: string | null;
    address?: string | null;
    contact_info?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    business_content?: string | null;
    representative?: string | null;
    board_members?: string | null;
    establishment_date?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freeschool".
 */
export interface Freeschool {
  id: number;
  summary?: {
    visualImage?: (number | null) | Media;
    schoolName?: string | null;
    introTitle?: string | null;
    free_school_desc?: string | null;
    description?: string | null;
    importantPointsTitle?: string | null;
    importantPoints?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    dialogueLeft?: string | null;
    dialogueRight?: string | null;
  };
  hero?: {
    catchphrase?: string | null;
    subcopy?: string | null;
    mainImage?: (number | null) | Media;
    decorativeImages?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  about?: {
    title?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    images?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    benefits?:
      | {
          text?: string | null;
          color?: ('bg-pink' | 'bg-blue') | null;
          id?: string | null;
        }[]
      | null;
  };
  message?: {
    title?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    repName?: string | null;
    repRole?: string | null;
  };
  merits?: {
    certificationTitle?: string | null;
    certificationItems?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    attendingTitle?: string | null;
    attendingBody?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  support?: {
    learningSupportTitle?: string | null;
    learningSupportBody?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    schoolRelationsTitle?: string | null;
    schoolRelationsBody?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  features?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        backgroundColor?: ('bg-lime' | 'bg-yellow' | 'bg-blue' | 'bg-pink') | null;
        id?: string | null;
      }[]
    | null;
  flow?:
    | {
        stepNumber?: string | null;
        title?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  schedule?: {
    image?: (number | null) | Media;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    scheduleItems?:
      | {
          time?: string | null;
          label?: string | null;
          image?: (number | null) | Media;
          icon?: string | null;
          rotation?: ('rotate-2' | 'rotate-1' | '-rotate-2' | '-rotate-1') | null;
          id?: string | null;
        }[]
      | null;
  };
  price?: {
    plans?:
      | {
          planName?: string | null;
          price?: string | null;
          note?: string | null;
          subtitle?: string | null;
          features?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          themeColor?: ('blue' | 'pink') | null;
          id?: string | null;
        }[]
      | null;
    annotation?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  intro_message?: T;
  mission?: T;
  history_years?: T;
  concept?:
    | T
    | {
        title?: T;
        subtitle?: T;
        main_image?: T;
        description_1?: T;
        description_2?: T;
        activities?:
          | T
          | {
              text?: T;
              color?: T;
              id?: T;
            };
        features?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  overview?:
    | T
    | {
        org_name?: T;
        address?: T;
        contact_info?: T;
        business_content?: T;
        representative?: T;
        board_members?: T;
        establishment_date?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freeschool_select".
 */
export interface FreeschoolSelect<T extends boolean = true> {
  summary?:
    | T
    | {
        visualImage?: T;
        schoolName?: T;
        introTitle?: T;
        free_school_desc?: T;
        description?: T;
        importantPointsTitle?: T;
        importantPoints?:
          | T
          | {
              text?: T;
              id?: T;
            };
        dialogueLeft?: T;
        dialogueRight?: T;
      };
  hero?:
    | T
    | {
        catchphrase?: T;
        subcopy?: T;
        mainImage?: T;
        decorativeImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        title?: T;
        body?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        benefits?:
          | T
          | {
              text?: T;
              color?: T;
              id?: T;
            };
      };
  message?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        repName?: T;
        repRole?: T;
      };
  merits?:
    | T
    | {
        certificationTitle?: T;
        certificationItems?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        attendingTitle?: T;
        attendingBody?: T;
      };
  support?:
    | T
    | {
        learningSupportTitle?: T;
        learningSupportBody?: T;
        schoolRelationsTitle?: T;
        schoolRelationsBody?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        backgroundColor?: T;
        id?: T;
      };
  flow?:
    | T
    | {
        stepNumber?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  schedule?:
    | T
    | {
        image?: T;
        body?: T;
        scheduleItems?:
          | T
          | {
              time?: T;
              label?: T;
              image?: T;
              icon?: T;
              rotation?: T;
              id?: T;
            };
      };
  price?:
    | T
    | {
        plans?:
          | T
          | {
              planName?: T;
              price?: T;
              note?: T;
              subtitle?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              themeColor?: T;
              id?: T;
            };
        annotation?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}